# Generated by Django 5.2.15 on 2026-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Содержание поста')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован/черновик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
            ],
        ),
    ]
